SkyCast/SkyCast/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from  django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/skycast/')),
    url(r'^skycast/', include('app_skycast.urls')),
    url(r'^admin/', admin.site.urls)
]

SkyCast/app_skycast/urls.py
from django.conf.urls import url

from . import views

app_name = 'app_skycast'
urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^current', views.current_view, name='current'),
    url(r'^forecast', views.forecast_view, name='forecast'),
    url(r'^historical_index', views.historical_index_view, name='historical_index'),
    url(r'historical', views.historical_view, name='historical')

]

SkyCast/app_skycast/models.py
from django.db import models

# Create your models here.

SkyCast/app_skycast/views.py
from django.shortcuts import render
import requests, datetime, calendar
from . import api_keys

# The keys we are hoping to find, ideally.
# There are more options, but sticking with the basics here; not sure if things like dew point and pressure
# count as "useful information"
# DarkSky API lists many as 'optional' so must check for presence of keys
# See https://darksky.net/dev/docs for explanations of data points
desired_historical_keys = ['precipProbability', 'temperatureHigh', 'temperatureLow']
hourly_desired_keys = ['icon', 'cloudCover', 'humidity', 'precipProbability', 'temperature', 'uvIndex']
daily_desired_keys = ['icon', 'cloudCover', 'humidity', 'precipProbability', 'precipIntensity',
                      'precipType', 'temperature', 'uvIndex', 'moonPhase', 'sunriseTime',
                      'sunsetTime', 'temperatureHigh', 'temperatureHighTime', 'temperatureLow',
                      'temperatureLowTime', 'uvIndex']
# implement alerts?
alerts_desired_keys = ['expires', 'severity', 'title', 'uri']

error = False;

def query_exists(street_name, city_name, num_queries, session):
    return_value = False;
    # for every previous query, compare against the current query's street/city name to prevent repeat queries
    for i in range(0, num_queries):
        if session['query'+str(i)]['street'] == street_name and session['query'+str(i)]['city'] == city_name:
            return_value = True;
    # if return true, this query has already been made and should not be stored as a new session value
    return return_value


def index_view(request):
    global error;
    context={}

    if error:
        context['error'] = 'True'
        error = False

    # if count not found, initialize count of how many queries have been made to 0
    if 'number_of_queries' not in request.session:
        request.session['number_of_queries'] = 0
    # if at at least one query has been made, we can let index know there are prior queries to display
    elif request.session['number_of_queries'] > 0:
        num_queries = request.session['number_of_queries']
        context["number_of_queries"] = num_queries
        # list of dicts, e.g. queries_list[0] = {'street': '1111 BlueWolf Avenue', ... }
        queries_list = [None] * request.session['number_of_queries']
        for i in range(0,num_queries):
            # e.g. queries_list[0] = request.session['query0']
            queries_list[i] = request.session['query'+str(i)]
        context['queries'] = queries_list
    return render(request, 'app_skycast/index.html', context)


def current_view(request):
    global error
    # retrieve form input values for the address
    street = request.POST['input1']
    city = request.POST['input2']
    state = request.POST['input3']

    # retrieve lat/lng with Google geocoding API
    location = get_lat_lng(street, city, state)

    # if lat/lng lookup didn't work, set global 'error' var to true and call index view
    if location[0] == None:
        error=True
        return index_view(request)

    query_number = request.session['number_of_queries']
    if query_exists(street, city, query_number, request.session):
        pass
    else:
        query_info = {'street': street, 'city': city, 'state': state}
        # starts at request.session['query0'], then 'query1', 'query2', ... etc.
        request.session['query'+str(query_number)] = query_info
        # incrementing number_of_queries
        request.session['number_of_queries'] += 1

    # use the lat/lng coordinates to query Dark Sky
    forecast_json = get_forecast(location[0], location[1], request.session)
    # picking out the section on current weather
    currently_json = forecast_json['currently']
    current_weather_info = {}

    # The keys we are hoping to find, ideally.
    # There are more options, but sticking with the basics here; not sure if things like dew point and pressure
    # count as "useful information"
    # DarkSky API lists many as 'optional' so must check for presence of each key
    desired_keys = ['cloudCover', 'humidity', 'icon', 'precipType', 'precipProbability',
                    'temperature', 'uvIndex']

    # For every desired key found in the 'currently' forecast response, add that key:value pair to
    # current_weather_info dict
    for key in desired_keys:
        current_weather_info[key] = '-'
        if key in currently_json:
            current_weather_info[key] = currently_json[key]

    # converting proportions to percents (e.g. 0.08 to 8)
    if 'cloudCover' in current_weather_info:
        current_weather_info['cloudCover'] *= 100

    if 'precipProbability' in current_weather_info:
        current_weather_info['precipProbability'] *= 100

    if 'humidity' in current_weather_info:
        current_weather_info['humidity'] *= 100

    # Converting epoch/POSIX/Unix timestamp to datetime.datetime object containing corresponding UTC time values
    utc_datetime = datetime.datetime.utcfromtimestamp(currently_json['time'])
    local_datetime = utc_datetime.replace(tzinfo=datetime.timezone.utc).astimezone(tz=None)
    second = local_datetime.second
    minute = local_datetime.minute
    hour = local_datetime.hour
    day = local_datetime.day
    month = local_datetime.month
    year = local_datetime.year

    context = {
        'lat': location[0],
        'lng': location[1],
        'street': street,
        'city': city,
        'state': state,
        'second': second,
        'minute': minute,
        'hour': hour,
        'day': day,
        'month': month,
        'year': year
    }

    for key in current_weather_info:
        context[key] = current_weather_info[key]

    return render(request, 'app_skycast/current.html', context)


def forecast_view(request):
    global error
    context = {}

    # retrieve form input values for the address
    street = request.POST['input1']
    city = request.POST['input2']
    state = request.POST['input3']

    # retrieve lat/lng with Google geocoding API
    location = get_lat_lng(street, city, state)

    # if lat/lng lookup didn't work, set global 'error' var to true and call index view
    if location[0] == None:
        error=True
        return index_view(request)

    context['lat'] = location[0]
    context['lng'] = location[1]

    query_number = request.session['number_of_queries']

    if query_exists(street, city, query_number, request.session):
        pass
    else:
        query_info = {'street': street, 'city': city, 'state': state}
        # starts at request.session['query0'], then 'query1', 'query2', ... etc.
        request.session['query'+str(query_number)] = query_info
        # incrementing number_of_queries
        request.session['number_of_queries'] += 1

    context['street'] = street
    context['city'] = city
    context['state'] = state

    # use the lat/lng coordinates to query Dark Sky
    forecast_json = get_forecast(location[0], location[1], request.session)

    # picking out the 'hourly' and 'daily' dicts
    hourly_json = forecast_json['hourly']
    daily_json = forecast_json['daily']

    # is there an alert?
    if 'alerts' in forecast_json:
        alerts_json = forecast_json['alerts']
        alerts_data = get_alerts_data(alerts_desired_keys, alerts_json)
        context['alerts_data'] = alerts_data

    # parse forecast response, store data of interest in daily and hourly lists of dicts
    daily_data = get_daily_data(daily_desired_keys, daily_json)
    hourly_data = get_hourly_data(hourly_desired_keys, hourly_json)


    # passing the entire list of dicts to the template
    context['daily_data'] = daily_data
    context['hourly_data'] = hourly_data

    return render(request, 'app_skycast/forecast.html', context)


def historical_index_view(request):
    context = {}
    context['remaining_api_requests'] = '1000'
    context['remaining_api_requests'] = request.session['remaining_api_requests']

    # retrieve form input values for the address inserted in index, to pre-populate the inputs in historical_index
    street = request.POST['input1']
    city = request.POST['input2']
    state = request.POST['input3']

    context['street'] = street
    context['city'] = city
    context['state'] = state

    return render(request, 'app_skycast/historical_index.html', context)


def historical_view(request):
    context={}

    # retrieve form input values for the address
    street = request.POST['input1']
    city = request.POST['input2']
    state = request.POST['input3']
    month = request.POST['month']
    year = request.POST['year']

    location = get_lat_lng(street, city, state)
    one_month_of_data = get_one_month_of_data(month, year, location[0], location[1], request.session)
    context['lat'] = location[0]
    context['lng'] = location[1]
    context['street'] = street
    context['city'] = city
    context['state'] = state
    context['month'] = month
    context['year'] = year

    # passing number of days so template knows max iteration value
    context['number_of_days'] = len(one_month_of_data)

    context['days_data'] = one_month_of_data

    return render(request, 'app_skycast/historical.html', context)

def get_forecast(lat, lng, session):
    key = api_keys.dark_sky_key
    req = requests.get('https://api.darksky.net/forecast/{}/{},{}'
                       .format(key, lat, lng))
    # setting cookie with remaining API queries
    session['remaining_api_requests'] = 1000 - int(req.headers['X-Forecast-API-Calls'])
    req_json = req.json()
    return req_json


def get_one_month_of_data(month, year, lat, lng, session):
    # X-Forecast-API-Calls as a response header

    # Number of days in a month varies... using calendar.monthrange to determine the correct # of days
    # reference as: days_data[day]['daily']['data'][0][key]
    # where day is an int in range (0, num_days_in_month), and key is one of the desired_historical_keys
    num_days_in_month = calendar.monthrange(int(year), int(month))[1]

SkyCast/app_skycast/templates/app_skycast/current.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app_skycast/current.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Current Weather</title>
</head>
<body>

<div id="current_weather_top">
    <span id="top_span">Current Weather for {{ street }} {{ city }}, {{ state }}</span>
</div>

<div id="lat_lng_div">
    Latitude: {{ lat }} Longitude: {{ lng }}
</div>

<div id="date_div">
    {{ hour }}:{{ minute }}:{{ second }} on {{ month }}/{{ day }}/{{ year }}
</div>

<table id="results_table">
    <tr>
        <th>Summary</th>
        <th>Temperature(F)</th>
        <th>Humidity</th>
        <th>Precipitation Type</th>
        <th>Precipitation Probability</th>
        <th>Cloud Cover</th>
        <th>UV Index</th>
    </tr>
    <tr>
        <td>{{ icon }}</td>
        <td>{{ temperature }}</td>
        <td>{{ humidity }}%</td>
        <td>{{ precipType }}</td>
        <td>{{ precipProbability }}%</td>
        <td>{{ cloudCover }}%</td>
        <td>{{ uvIndex }}</td>
    </tr>
</table>


<button id="back_to_index_button" onclick="window.location.replace('{% url 'app_skycast:index' %}')">
    Return to Index
</button>




</body>
</html>

SkyCast/app_skycast/templates/app_skycast/forecast.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app_skycast/forecast.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forecast</title>

    <script>
        var daily;
        var hourly;
        var day=0;
        var hour=0;
        var daily_keys = ['icon', 'temperatureHigh', 'temperatureLow', 'uvIndex', 'sunriseTime', 'sunsetTime', 'moonPhase']
        var hourly_keys = ['full_time', 'icon', 'cloudCover', 'humidity', 'precipProbability', 'temperature', 'uvIndex']

        $( document ).ready(function() {
            daily = {{ daily_data|safe }};
            hourly = {{ hourly_data|safe }};

            set_daily_info()
            set_hourly_info()
        });

        function next_day(){
            if(day<6){
                day++;
                set_daily_info()
            }
        }

        function last_day(){
            if(day>0){
                day--;
                set_daily_info()
            }
        }

        function next_hours(){
            // will display 12 hour chunks, to a max of 48 hours in the future
            // hour value of 36 means we are displaying 36-48, so 36 is max
            if(hour<36){
                hour+=12
                set_hourly_info()
            }
        }

        function last_hours(){
            // will display 12 hour chunks, to a max of 48 hours in the future
            // 12-12 = 0
            if(hour>11){
                hour-=12
                set_hourly_info()
            }
        }

        function set_daily_info(){
            // tr:nth-child(2) is the 2nd row, which is the first row after the header row.
            // .children returns all children of the second row, i.e. the <td> tags
            var a = $('#daily_table tr:nth-child(2)').children()

            // iterate over the <td>s, set each one's text
            for(var i=0; i<7; i++){
                // e.g. daily[0]['icon']
                var text = daily[day][daily_keys[i]]
                $(a[i]).html(text)
            }

            // must also change the displayed date to the correct month/day
            var month = daily[day]['month']
            var today = daily[day]['day']
            $('#daily_time_div').html(month + "/" + today)
        }

        function set_hourly_info(){
            // iterate through each of the seven rows row (rows 2-8)
            for(var n=2; n<14; n++){
                // getting the child tds of the nth row
                var row_tds = $('#hourly_table tr:nth-child(' + n + ')').children()
                for(var j=0; j<7; j++){
                    // start at hour+0, end at hour+11 for a 12 hour chunk. e.g. 00:00 to 11:00
                    var temp_text = hourly[hour+n-2][hourly_keys[j]]
                    $(row_tds[j]).html(temp_text)
                }
            }

            // must also change hourly_time_div to reflect the new range of hours
            var month1 = hourly[hour]['month']
            var day1 = hourly[hour]['day']
            var hour1 = hourly[hour]['hour']

            var month2 = hourly[hour+11]['month']
            var day2 = hourly[hour+11]['day']
            var hour2 = hourly[hour+11]['hour']

            var hourly_time_text = month1 + "/" + day1 + " at " + hour1 + ":00 " +
                    "to " + month2 + "/" + day2 + " at " + hour2 + ":00"
            $('#hourly_time_div').html(hourly_time_text)
        }
    </script>

</head>
<body>
<div id="forecast_weather_top">
    <span id="top_span">Forecast for {{ street }} {{ city }}, {{ state }}</span>
</div>
<div id="lat_lng_div">
    Latitude: {{ lat }} Longitude: {{ lng }}
</div>
<div id = "daily_time_div">
    {{ daily_data.0.month }}/{{ daily_data.0.day }}
</div>
<div id="daily_div">
    <button id="daily_prev_button" onclick="last_day()">Previous Day</button>
    <button id="daily_next_button" onclick = "next_day()">Next Day</button>
    <table id="daily_table">
        <tr>
            <th>Summary</th>
            <th>High Temp</th>
            <th>Low Temp</th>
            <th>UV Index</th>
            <th>Sunrise</th>
            <th>Sunset</th>
            <th>Moon Phase</th>
        </tr>
        <tr>
            <td id="d1">-a</td>
            <td id="d2">a</td>
            <td id="d3">b</td>
            <td id="d4">c</td>
            <td id="d5">d</td>
            <td id="d6">e</td>
            <td id="d7">f</td>
        </tr>
    </table>
</div>
<div id="hourly_time_div">
    {{ hourly_data.0.month }}/{{ hourly_data.0.day }} at {{ hourly_data.0.hour }}:00 to
    {{ hourly_data.11.month }}/{{ hourly_data.11.day }} at {{ hourly_data.11.hour }}:00
</div>
<div id="hourly_div">
    <button id="hourly_prev_button" onclick="last_hours()">Previous 12 Hours</button>
    <button id="hourly_next_button" onclick="next_hours()">Next 12 Hours</button>
    <table id="hourly_table">
        <tr>
            <th>Hour</th>
            <th>Summary</th>
            <th>Cloud Cover</th>
            <th>Humidity</th>
            <th>Chance of Precip</th>
            <th>Temperature</th>
            <th>UV Index</th>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>



    </table>
</div>

<button id="back_to_index_button" onclick="window.location.replace('{% url 'app_skycast:index' %}')">
    Return to Index
</button>

</body>
</html>

SkyCast/app_skycast/templates/app_skycast/historical.html
{% load static %}


<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'app_skycast/historical.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <meta charset="UTF-8">
    <title>Historic</title>
    <script>
        $(document).ready(function() {
            var number_of_days = {{ number_of_days }};
            var days_data = {{ days_data|safe }};
            var day_nums = []
            var high_temp_data = []
            var low_temp_data = []
            var prob_precip_data = []
            // creating x-axis values for the chart... ['1', '2', '3', '4', ..., number_of_days]
            for(var i=0; i<parseInt(number_of_days); i++){
                day_nums.push((i+1).toString());
                high_temp_data.push(days_data[i]['temperatureHigh']);
                low_temp_data.push(days_data[i]['temperatureLow']);
                prob_precip_data.push(days_data[i]['precipProbability']);
            }

            Highcharts.chart('container', {
                chart: {
                    zoomType: 'xy'
                },
                title: {
                    text: 'Temperature Extremes & Chance of Precipitation for {{ street }} {{ city }}, {{ state }}'
                },
                subtitle:{
                    text: '{{ month }}/{{ year }}'
                },
                xAxis: [{
                    categories: day_nums,
                    crosshair: true
                }],
                yAxis: [{ // Primary yAxis
                    labels: {
                        format: '{value}°F',
                        style: {
                            color: Highcharts.getOptions().colors[1]
                        }
                    },
                    title: {
                        text: 'Temperature',
                        style: {
                            color: Highcharts.getOptions().colors[1]
                        }
                    }
                }, { // Secondary yAxis
                    min: 0,
                    max: 1,
                    tickInterval: 0.1,
                    title: {
                        text: 'Chance of Precipitation',
                        style: {
                            color: Highcharts.getOptions().colors[0]
                        }
                    },
                    labels: {
                        format: '{value}',
                        style: {
                            color: Highcharts.getOptions().colors[0]
                        }
                    },
                    opposite: true
                }],
                tooltip: {
                    shared: true
                },
                legend: {
                    layout: 'vertical',
                    align: 'left',
                    verticalAlign: 'top',
                    x: 60,
                    y: 50,
                    floating: true,
                    backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
                },
                series: [{
                    name: 'Chance of Precipitation',
                    type: 'column',
                    yAxis: 1,
                    data: prob_precip_data,
                    tooltip: {
                        valueSuffix: '%'
                    }

                }, {
                    name: 'High Temperature',
                    type: 'spline',
                    data: high_temp_data,
                    tooltip: {
                        valueSuffix: '°F'
                    },

                }, {
                    name: 'Low Temperature',
                    type: 'spline',
                    data: low_temp_data,
                    tooltip: {
                        valueSuffix: '°F'
                    },
                }]
            });
        });
    </script>
</head>
<body>

<div id="container">

</div>

<span id="license">Charts generated by <a href="https://www.highcharts.com/">Highcharts</a>
    under a free non-commercial <a href="https://creativecommons.org/licenses/by-nc/3.0/legalcode">license</a>
</span>

<button id="return_to_index" onclick="window.location.replace('{% url 'app_skycast:index' %}')">Return to Index</button>

</body>
</html>

SkyCast/app_skycast/templates/app_skycast/historical_index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app_skycast/historical_index.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Historical Data - Index</title>
    <script>
        function is_a_form_input_empty(){
            var a = document.forms['dates'].input1.value;
            var b = document.forms['dates'].input2.value;
            var c = document.forms['dates'].input3.value;
            var d = document.forms['dates'].input4.value;
            var e = document.forms['dates'].input5.value;
            var f = document.forms['dates'].input6.value;

            if(a==null || a=="", b==null || b=="", c==null || c=="", d==null || d=="", e==null || e=="", f==null || f==""){
                return true
            }
            else{
                return false
            }
        }

        $(document).ready(function(){
            if(is_a_form_input_empty()){
                alert('Please enter both a starting and ending month, day, and year.')
            }
            else{
                document.getElementById("form1").action = e;
                document.getElementById("form1").submit();
            }
        })
    </script>
</head>
<body>
<div id="input_div">
    <span id="dates_explanation">
        Enter a month and year (1970-2016) to show historical weather information for that month.
        This may take some time.
    </span>
    <form id="input_form" action="{% url 'app_skycast:historical' %}" method="POST">
        {% csrf_token %}
        <input required="required" type="text" name="input1" id="input1" placeholder="Street Address" value="{{ street }}">
        <input required="required" type="text" name="input2" id="input2" placeholder="City" value="{{ city }}">
        <input required="required" type="text" name="input3" id="input3" placeholder="State" value="{{ state }}">
        <select name="month" id="month">
            <option selected disabled>Choose a Month</option>
            <option value="01">January</option>
            <option value="02">February</option>
            <option value="03">March</option>
            <option value="04">April</option>
            <option value="05">May</option>
            <option value="06">June</option>
            <option value="07">July</option>
            <option value="08">August</option>
            <option value="09">September</option>
            <option value="10">October</option>
            <option value="11">November</option>
            <option value="12">December</option>
        </select>
        <!-- need error checking to detect a month in the future -->
        <input type="number" id="year_input" name="year" required="required" placeholder="Year" min="1970" max="2016">
        <input type="submit" id="submit_button" value="Submit">
    </form>
    <span id="remaining_API_calls">Note:<br>Free use of the Dark Sky API is limited to 1000 requests per 24 hour period.
    <br>~30 requests are required to retrieve the month of data used for historical lookup. <br>
        Remaining requests: <br> <b>{{ remaining_api_requests }}</b></span>
</div>

<button id="return_to_index" onclick="window.location.replace('{% url 'app_skycast:index' %}')">Return to Index</button>


</body>
</html>

SkyCast/app_skycast/templates/app_skycast/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app_skycast/index.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SkyCast Index</title>
    <script>
        var queries_text;
        var num_queries;

        function set_action_submit(e){
            if(is_a_form_input_empty()){
                alert("Please enter a valid street address, city, and state.")
            }
            else{
                document.getElementById("form1").action = e;
                document.getElementById("form1").submit();
            }
        }

        function is_a_form_input_empty(){
            var a = document.forms['form1'].input1.value;
            var b = document.forms['form1'].input2.value;
            var c = document.forms['form1'].input3.value;

            if(a==null || a=="", b==null || b=="", c==null || c==""){
                return true
            }
            else{
                return false
            }
        }

        function build_select(){
            var s= document.getElementById('query_select');
            for(var i=0; i<num_queries;i++){
                var street = queries_text[i]['street'];
                var state = queries_text[i]['state'];
                var city = queries_text[i]['city'];
                var text = street + " " + city + ", " + state;

                // Option(text, value)
                s.options[i]= new Option(text, i);
            }
        }

        function query_change(e){
            // when user changes their previous queries selection, automatically populate the inputs with the
            // corresponding street/city/state information
            $('#input1').val(queries_text[e]['street']);
            $('#input2').val(queries_text[e]['city']);
            $('#input3').val(queries_text[e]['state']);
        }

        $( document ).ready(function() {
            queries_text = {{ queries|safe }}
            num_queries = {{ number_of_queries }}
            build_select()
            {% if error %}
                alert('Could not complete request - geolocation failed for that address.')
            {% endif %}
        });
    </script>
</head>
<body>

<div id="title_area">
    Welcome to SkyCast
</div>
<form action="javascript:void(0)" method="post" id="form1" name="form1">
    {% csrf_token %}
    <div id="input_div">
        <input required="required" type="text" name="input1" id="input1" placeholder="Street Address">
        <input required="required" type="text" name="input2" id="input2" placeholder="City">
        <input required="required" type="text" name="input3" id="input3" placeholder="State">
    </div>
    <div id="buttons_div">
        <input type="button" onclick="set_action_submit('{% url 'app_skycast:current' %}')" name="button" value="Current">
        <input type="button" onclick="set_action_submit('{% url 'app_skycast:forecast' %}')" name="button" value="Forecast">
        <input type="button" onclick="set_action_submit('{% url 'app_skycast:historical_index' %}')" name="button" value="Historical">
    </div>
</form>

<!-- only include the selection box for past queries if there are any queries to show -->

<div id="query_select_div">
    <select id="query_select" size="5" onchange="query_change(value)">
    </select>
</div>


<a href="https://darksky.net/poweredby/" id="dark_sky_acknowledgement">Powered by Dark Sky</a>



</body>
</html>